"""neural scheduler tables and FSRS columns

Revision ID: 2444c2e5c265
Revises: 126413412b33
Create Date: 2026-04-12 00:15:21.533610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2444c2e5c265'
down_revision: Union[str, None] = '126413412b33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_models',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('strategy', sa.String(length=10), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id')
    )
    op.create_index(op.f('ix_scheduler_models_user_id'), 'scheduler_models', ['user_id'], unique=False)
    op.add_column('flashcard_progress', sa.Column('stability', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('flashcard_progress', sa.Column('difficulty', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('flashcard_progress', sa.Column('last_grade', sa.Integer(), nullable=True))
    op.add_column('flashcard_progress', sa.Column('fsrs_review_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flashcard_progress', 'fsrs_review_count')
    op.drop_column('flashcard_progress', 'last_grade')
    op.drop_column('flashcard_progress', 'difficulty')
    op.drop_column('flashcard_progress', 'stability')
    op.drop_index(op.f('ix_scheduler_models_user_id'), table_name='scheduler_models')
    op.drop_table('scheduler_models')
    # ### end Alembic commands ###
