"""scheduler_models: add created_at and the missing user/course foreign keys

The table was created by an autogenerated migration that dropped three things
the ORM model declares: the ``created_at`` column from ``TimestampMixin`` and
the ``users``/``courses`` foreign keys (both ``ON DELETE CASCADE``).

The missing column is not cosmetic. ``SchedulerModel`` inherits
``TimestampMixin``, so SQLAlchemy emits ``scheduler_models.created_at`` in
every SELECT, which means ``POST /api/flashcards/sets/{set_id}/review``
(app/api/flashcards.py) raises ``UndefinedColumnError`` and 500s on every
call. The whole spaced-repetition review path is unusable until this lands.

The absent foreign keys also left orphan rows possible: deleting a user or a
course left their scheduler rows behind, since nothing enforced the cascade
the model promises.

Revision ID: a1c4f8e2d905
Revises: e2f9a4b71c60
Create Date: 2026-08-07
"""

from alembic import op
import sqlalchemy as sa


revision = "a1c4f8e2d905"
down_revision = "e2f9a4b71c60"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Backfill from updated_at so pre-existing rows get a sensible instant
    # rather than the migration's wall clock; then enforce NOT NULL.
    op.add_column(
        "scheduler_models",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.execute(
        "UPDATE scheduler_models SET created_at = COALESCE(updated_at, now()) "
        "WHERE created_at IS NULL"
    )
    op.alter_column(
        "scheduler_models",
        "created_at",
        nullable=False,
        server_default=sa.text("now()"),
    )

    # Drop rows that can no longer satisfy the FKs before adding them, so the
    # migration cannot fail on legacy orphans it is meant to make impossible.
    op.execute(
        "DELETE FROM scheduler_models sm "
        "WHERE NOT EXISTS (SELECT 1 FROM users u WHERE u.id = sm.user_id) "
        "   OR NOT EXISTS (SELECT 1 FROM courses c WHERE c.id = sm.course_id)"
    )
    op.create_foreign_key(
        "scheduler_models_user_id_fkey",
        "scheduler_models",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "scheduler_models_course_id_fkey",
        "scheduler_models",
        "courses",
        ["course_id"],
        ["id"],
        ondelete="CASCADE",
    )


def downgrade() -> None:
    op.drop_constraint(
        "scheduler_models_course_id_fkey", "scheduler_models", type_="foreignkey"
    )
    op.drop_constraint(
        "scheduler_models_user_id_fkey", "scheduler_models", type_="foreignkey"
    )
    op.drop_column("scheduler_models", "created_at")
