import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { expect, type Page, type Request, type ConsoleMessage } from "@playwright/test";

/**
 * Shared fixtures for the live-stack e2e suite.
 *
 * Seeded ids are read from `.seed-manifest.json`, which the demo seeds write on
 * every run. They MUST NOT be hardcoded: the seeds purge and recreate their
 * rows, so any literal UUID goes stale the first time anyone re-seeds, and a
 * test that asserts on workspace chrome will pass happily against a course that
 * no longer exists, which is worse than failing.
 */

// Playwright transpiles specs to CJS, so `import.meta.url` is unavailable here.
// Resolve from the process cwd instead, accepting either `frontend/` (the
// documented invocation directory) or the repo root.
const MANIFEST_CANDIDATES = [
  resolve(process.cwd(), "e2e", ".seed-manifest.json"),
  resolve(process.cwd(), "frontend", "e2e", ".seed-manifest.json"),
];
const MANIFEST_PATH =
  MANIFEST_CANDIDATES.find((p) => existsSync(p)) ?? MANIFEST_CANDIDATES[0];

export interface SeedManifest {
  publishedCourseId: string;
  publishedCourseCode: string;
  draftCourseId: string;
  draftCourseCode: string;
  enrollCode: string;
  teacherEmail: string;
  studentEmail: string;
  pendingEmail: string;
  password: string;
  checkpointClosedId: string;
  checkpointOpenId: string;
  checkpointDraftId: string;
  practiceQuizId: string;
  gradedQuizId: string;
  activityId: string;
}

/**
 * Placeholder used when the manifest is absent. The manifest is gitignored
 * (it is regenerated by the seeds), so CI and the infra-free suites have no
 * copy, and Playwright evaluates spec module scope during collection even for
 * tests that will `skip`. Throwing here would fail collection for the whole
 * project rather than skipping the live-stack specs, so return placeholders and
 * let the `MELI_LIVE_STACK` guard do its job.
 */
const PLACEHOLDER: SeedManifest = {
  publishedCourseId: "00000000-0000-0000-0000-000000000000",
  publishedCourseCode: "UNSEEDED",
  draftCourseId: "00000000-0000-0000-0000-000000000000",
  draftCourseCode: "UNSEEDED",
  enrollCode: "UNSEEDED",
  teacherEmail: "unseeded@example.invalid",
  studentEmail: "unseeded@example.invalid",
  pendingEmail: "unseeded@example.invalid",
  password: "unseeded",
  checkpointClosedId: "00000000-0000-0000-0000-000000000000",
  checkpointOpenId: "00000000-0000-0000-0000-000000000000",
  checkpointDraftId: "00000000-0000-0000-0000-000000000000",
  practiceQuizId: "00000000-0000-0000-0000-000000000000",
  gradedQuizId: "00000000-0000-0000-0000-000000000000",
  activityId: "00000000-0000-0000-0000-000000000000",
};

let cached: SeedManifest | undefined;

export function seed(): SeedManifest {
  if (cached) return cached;
  let raw: string;
  try {
    raw = readFileSync(MANIFEST_PATH, "utf-8");
  } catch {
    if (process.env.MELI_LIVE_STACK === "1") {
      throw new Error(
        `Missing ${MANIFEST_PATH}. Run the demo seeds first:\n` +
          `  backend/.venv/Scripts/python.exe seed_demo.py\n` +
          `  node frontend/scripts/seed-auth.mjs\n` +
          `  backend/.venv/Scripts/python.exe seed_demo_content.py`
      );
    }
    cached = PLACEHOLDER;
    return cached;
  }
  cached = JSON.parse(raw) as SeedManifest;
  return cached;
}

export const NAV_TIMEOUT = 45_000;
export const VISIBLE_TIMEOUT = 20_000;

export async function signIn(page: Page, email: string): Promise<void> {
  const { password } = seed();
  await page.goto("/sign-in");
  await page.fill('input[name="email"]', email);
  await page.fill('input[name="password"]', password);
  await page.click('button[type="submit"]');
}

export async function signInAs(
  page: Page,
  role: "teacher" | "student"
): Promise<void> {
  const m = seed();
  await signIn(page, role === "teacher" ? m.teacherEmail : m.studentEmail);
  await page.waitForURL(new RegExp(`/${role}/dashboard`), {
    timeout: NAV_TIMEOUT,
  });
}

/** An app-level crash (error boundary / Next overlay), as opposed to a
 *  legitimate empty or waiting state. */
export async function expectNoAppError(page: Page): Promise<void> {
  await expect(
    page.getByText(/application error|something went wrong|unhandled runtime/i)
  ).toHaveCount(0);
}

export interface PageProblems {
  consoleErrors: string[];
  pageErrors: string[];
  failedRequests: string[];
  serverErrors: string[];
}

/**
 * Attach listeners that record everything a route does wrong while it loads:
 * console errors, uncaught exceptions, network failures, and 5xx/4xx API
 * responses. This is the instrument that catches the defects a "does the
 * heading render" assertion sails straight past.
 */
export function watchForProblems(page: Page): PageProblems {
  const problems: PageProblems = {
    consoleErrors: [],
    pageErrors: [],
    failedRequests: [],
    serverErrors: [],
  };

  // Noise that is not a product defect: browser-level warnings we do not
  // control, and Next's dev-only HMR chatter.
  const IGNORED = [
    /favicon/i,
    /Download the React DevTools/i,
    /\[Fast Refresh\]/i,
    /webpack-hmr/i,
    /_next\/static\/development/i,
    // Vercel Analytics/Speed Insights only resolve on a Vercel deployment. In
    // local dev the browser blocks the debug script (ERR_BLOCKED_BY_ORB); that
    // is an artefact of running off-platform, not a product defect.
    /va\.vercel-scripts\.com/i,
    /vitals\.vercel-insights\.com/i,
  ];
  const ignored = (text: string) => IGNORED.some((re) => re.test(text));

  page.on("console", (msg: ConsoleMessage) => {
    if (msg.type() !== "error") return;
    const text = msg.text();
    if (!ignored(text)) problems.consoleErrors.push(text);
  });

  page.on("pageerror", (err: Error) => {
    if (!ignored(err.message)) problems.pageErrors.push(err.message);
  });

  page.on("requestfailed", (req: Request) => {
    const url = req.url();
    const failure = req.failure()?.errorText ?? "unknown";
    // Playwright reports user-initiated aborts on navigation as failures.
    if (failure.includes("ERR_ABORTED")) return;
    if (!ignored(url)) problems.failedRequests.push(`${url}: ${failure}`);
  });

  page.on("response", (res) => {
    const status = res.status();
    const url = res.url();
    if (status < 400 || ignored(url)) return;
    // 401 on the Better Auth session probe is expected while signed out.
    if (status === 401 && /\/api\/auth\//.test(url)) return;
    problems.serverErrors.push(`${status} ${url}`);
  });

  return problems;
}

export function summarizeProblems(p: PageProblems): string {
  const lines: string[] = [];
  if (p.pageErrors.length) lines.push(`uncaught: ${p.pageErrors.join(" | ")}`);
  if (p.consoleErrors.length)
    lines.push(`console: ${p.consoleErrors.join(" | ")}`);
  if (p.serverErrors.length) lines.push(`http: ${p.serverErrors.join(" | ")}`);
  if (p.failedRequests.length)
    lines.push(`net: ${p.failedRequests.join(" | ")}`);
  return lines.join("\n");
}

export function hasProblems(p: PageProblems): boolean {
  return (
    p.pageErrors.length > 0 ||
    p.consoleErrors.length > 0 ||
    p.serverErrors.length > 0 ||
    p.failedRequests.length > 0
  );
}
